### ISSUE TITLE
Allow download of dataset metadata as well

### ISSUE THREAD

**Issue by jqnatividad** [talos/opendatacache#7]
The system already caches the metadata, why not expose it as well as a downloadable resource?

e.g. for http://www.opendatacache.com/data.cityofnewyork.us/api/views/22b5-sytd/rows.csv
have 
http://www.opendatacache.com/data.cityofnewyork.us/api/views/22b5-sytd/metadata.json

**Comment by talos** [comment]
@jqnatividad It is! Follows the same path as it would be found on Socrata.  See:

http://www.opendatacache.com/data.cityofnewyork.us/api/views/22b5-sytd.json

It's just a proxy.  So any qualifying URL (stuff in /api/views, /download, and a few other places) should appear exactly as it does on Socrata, unless it's been cached in which case it will be pulled from S3 instead.
